# Defines which flag will be assigned to each color of a property
GREEN_PROPERTY = 0
DARK_BLUE_PROPERTY = 1
LIGHT_BLUE_PROPERTY = 2
RED_PROPERTY = 3
LIGHT_GREEN_PROPERTY = 4
YELLOW_PROPERTY = 5
ORANGE_PROPERTY = 6
BROWN_PROPERTY = 7
PINK_PROPERTY = 8
BLACK_PROPERTY = 9
RAINBOW_PROPERTY = 10

# Defines flags for each of the action cards.
DEAL_BREAKER = 30
DEBT_COLLECTOR = 31
DOUBLE_RENT = 32
FORCED_DEAL = 33
HOTEL = 34
HOUSE = 35
ITS_MY_BIRTHDAY = 36
JUST_SAY_NO = 37
PASS_GO = 38
SLY_DEAL = 39