ACTION_CARD = 0
PROPERTY_CARD = 1
WILD_PROPERTY_CARD = 2
RENT_CARD = 3
MONEY_CARD = 4

GREEN_PROPERTY = 0
DARK_BLUE_PROPERTY = 1
LIGHT_BLUE_PROPERTY = 2
RED_PROPERTY = 3
LIGHT_GREEN_PROPERTY = 4
YELLOW_PROPERTY = 5
ORANGE_PROPERTY = 6
BROWN_PROPERTY = 7
PINK_PROPERTY = 8
BLACK_PROPERTY = 9
RAINBOW_PROPERTY = 10
